project_id = "inrivbbifhraowqlqzsp"

[functions.create-site]
verify_jwt = true

[functions.github-installation-details]
verify_jwt = true

[functions.fetch-site-assets]
verify_jwt = true

[functions.create-site-assets-pr]
verify_jwt = true

[functions.upload-site-asset]
verify_jwt = true

[functions.fetch-asset-content]
verify_jwt = true

[functions.list-directory-assets]
verify_jwt = true

[functions.delete-site-asset]
verify_jwt = true

[functions.create-invitation]
verify_jwt = true

[functions.accept-invitation]
verify_jwt = true

[functions.create-asset-share]
verify_jwt = true

[functions.guest-upload-asset]
verify_jwt = false

